
---
author: 
- William "HousedHorse" Findlay
title: Random Map Scripting for AoE II HD 
date: \today
bibliography: /home/housedhorse/.bibs/uni.bib
csl: /home/housedhorse/.bibs/ieee.csl
subparagraph: yes
header-includes: |
  ``` {=latex}
  \usepackage{float}
  \usepackage{listings}
  \usepackage[hang,bf]{caption}
  \usepackage{framed}
  \usepackage[section]{placeins}

  \allowdisplaybreaks

  % fancy headers/footers
  \makeatletter
  \usepackage{fancyhdr}
  \lhead{\@author}
  \chead{}
  \rhead{\@title}
  \lfoot{}
  \cfoot{\thepage}
  \rfoot{}
  \renewcommand{\headrulewidth}{0.4pt}
  \pagestyle{plain}
  \pagestyle{fancy}

  \usepackage{amsmath, amsfonts,amssymb, amsthm}
  \usepackage{siunitx}

  \usepackage{setspace}
  \usepackage{changepage}
  \usepackage{titlesec}
  \usepackage{aliascnt}

  \floatplacement{figure}{!htb}
  \floatplacement{table}{!htb}
  \floatplacement{listing}{!htb}
  \lstset{mathescape=true,numbers=left,breaklines=true,frame=single,language=C,captionpos=b,abovecaptionskip={\abovecaptionskip},belowcaptionskip={\belowcaptionskip},aboveskip=\intextsep}
  \setlength{\captionmargin}{1in}

  \newgeometry{margin=1in}

  \newtheoremstyle{plain}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\itshape}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{definition}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{remark}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\itshape} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \theoremstyle{plain}

  % define theorem
  \newtheorem{theorem}{Theorem}[section]
  \providecommand*{\theoremautorefname}{Theorem}

  % define lemma
  \newtheorem{lemma}{Lemma}[section]
  \providecommand*{\lemmaautorefname}{Lemma}

  % define claim
  \newtheorem{claim}{Claim}[section]
  \providecommand*{\claimautorefname}{Claim}

  % define corollary
  \newtheorem{corollary}{Corollary}[section]
  \providecommand*{\corollaryautorefname}{Corollary}

  % define proposition
  \newtheorem{proposition}{Proposition}[section]
  \providecommand*{\propositionautorefname}{Proposition}

  % define conjecture
  \newtheorem{conjecture}{Conjecture}[section]
  \providecommand*{\conjectureautorefname}{Conjecture}

  \theoremstyle{remark}

  % define observation
  \newtheorem{observation}{Observation}[section]
  \providecommand*{\observationautorefname}{Observation}

  % define remark
  \newtheorem{remark}{Remark}[section]
  \providecommand*{\remarkautorefname}{Remark}

  \theoremstyle{definition}

  % define example
  \newtheorem{example}{Example}[section]
  \providecommand*{\exampleautorefname}{Example}

  % define definition
  \newtheorem{definition}{Definition}[section]
  \providecommand*{\definitionautorefname}{Definition}

  \newcommand{\blackbox}{\hfill$\blacksquare$}
  \usepackage{tikz}
  \newcommand*\circled[1]{\tikz[baseline=(char.base)]{
              \node[shape=circle,draw,inner sep=2pt] (char) {#1};}}

  \let\lil\lstinputlisting
  \usepackage{afterpage}
  \usepackage{xcolor}
  \hypersetup{colorlinks, allcolors=., urlcolor=blue}
  ```
output:
  pdf_document:
    number_sections: true
    fig_crop: true
    fig_caption: true
    keep_tex: true
---
\newpage
\pagestyle{plain}
\tableofcontents
\newpage
\lstlistoflistings
\newpage
\pagestyle{fancy}





# About the Author

[William "HousedHorse" Findlay](http://www.wfindlay.com/) has been playing Age of Empires II since
his father introduced it to him when William was three years old.

He has played Starcraft II at a semi-professional level, reaching rank number
5 on the North American server. He is also 2100 rated on Age of Empires II HD.

William is an admin of the Age of Empires Memes Community group on Facebook, an
Age fan page with over 30,000 members.

He works as a teaching assistant in the Computer Science department at Carleton University
in Ottawa, Ontario, Canada. William enjoys scripting and coding and sees
random map scripting as a great way to blend his passion for programming and
his love of Age of Empires II.



# What is RMS?

Welcome to my **random map scripting** guide! If you are here, you probably
have some general idea of what an RMS is. If not, don't worry! I will be explaining
all about random map scripting in this section and all the great things you can do with it.

When you think about custom games in Age of Empires II, typically a scenario is the first
thing that comes to mind. Scenarios are great. You can do lots of cool things in them.
The only issue with a scenario is that it is the same thing every time. And if a mapmaker
does not take great care, a scenario can easily become too unbalanced for competitive play.

Age of Empires takes care of this problem with the concept of random maps.
While a lot of games use "scenarios" for their competitive matches, Age of Empires
competitive matches are played **exclusively** on random maps. By learning how
to create random map scripts of your own, you can create custom map types
for players to enjoy competitively.

Some examples of random maps include Arabia, Arena, Black Forest, Nomad, and many,
many more. These are all examples of maps that come with the base game. However, if we
journey to the `Custom` section in the lobby screen, we can see a list of **custom random
maps**. In this guide, we are going to learn to create maps like these.

## Why is it Called a Random Map Script?

Age of Empires II uses a random map generator to create its random maps.
A random map generator is an **algorithm** which takes a random value called a seed
and carries out a series of steps to output a full randomized map.

By default, the generator will spit out a flat grassy map with no resources and
a town center, scout, and villagers for every player. But this is super boring.
How do we make it do interesting things?

Well, it turns out we can write a text file called a **random map script**. This text
file is structured in a special way so the random map generator can read it and use it
as a guideline for map generation.

For example, we could set the terrain to be snowy instead of the default grass and add
randomly placed lakes and resources.
The generator will read these instructions and adjust its random output so the map
fits our guidelines.  Now we're starting to have something that looks
more like a real map!




# How to Use This Guide

In this section we will detail exactly how to read this guide. We will be going over
some simple conventions we use to make reading the guide simpler and following that
up with some basic RMS\footnote{Random Map Script.} syntax\footnote{The rules we have to
follow so the generator can read our script.} to get you started and thinking about
what a proper script looks like.

## Guide Conventions

In this guide, we will be showing script examples throughout. The examples will be shown
in the form of code blocks which look like \autoref{example-block}.

\lil[caption={[Example code block]An example RMS code block.},label={example-block}]{code/3/intro.rms}

Each block will be labeled with a **listing number**. This is the number that will be
referenced in text. If you see a listing number in the text, you can take a look
nearby for the accompanying sample code.

Code blocks like in \autoref{example-block} will be surrounded by a black box. To the
left of the blocks, you will see line numbers for your reference. If you are copying the
sample code, **do not copy the line numbers**. They are just for your reference.


## Basic RMS Syntax

In this subsection, we will learn about some basic syntax to get you started
thinking about what an RMS should look like. Syntax is the way our script has to be
formatted in order to allow the game to read it properly. Syntax is **super important**
or your script will **break horribly** and you will be sad.

### Comments

Comments are bits of text that you can read and understand but the random map generator
ignores completely.
It is important to comment your script so that you can come back and understand it
later.

I also like to use comments in my script template so that when I am making a new
script I have easy access to all the constants and functions I need. I will be going
over my template much later in the guide.

**So, how do we write a comment?** It's pretty easy.
Comments start with `/*` and end with `*/` . The `/*` and `*/` do not
need to be on the same line and in this way you can write a comment that spans
multiple lines. A comment can be as short or as long as you like.
See \autoref{comment-example} for an example.

\lil[caption={[Comments]The two types of comments in a random map script. Note the /* and */
which denote the comment's beginning and end. Also note the space between the beginning
and end of a comment and the comment itself.},label={comment-example},float]{code/3/comment-example.rms}

As you can see in \autoref{comment-example}, it's pretty easy to make a comment.
**But there is one super important thing to watch out for!** When you write a comment
it is **required** to leave a space between the `/*` and the first word and the `*/`
and the last word. **If you do not use those spaces your script will not work**.


### Constants
A constant is a way of binding a *value* to a *name* **permanently** in your script.
What kind of value do I mean? Every object and terrain in the game is represented by
a *number* that the random map generator understands. To make it so you don't have to
memorize a list of weird numbers, the game *predefines* many constants for you.

For example instead of typing `1234`, I can type `GRASS` and the game knows that I'm talking
about the grassy terrain.

However, some objects and terrains do not come with a predefined name. Instead, we have to look up
the number and give it a name of our own. There are a few rules for doing this:

1. The name you choose must not already be assigned to *another number* either by you *or* by the game.
1. The number you choose must be assigned to an actual object in the game. Choosing a random number may cause
   the game to crash!
1. You define your constant as follows: `#const NAME NUMBER`

Suppose for example, we wanted to include a dead tree in our map. Spooky. We simply do it
as shown in \autoref{constex}.

\lil[caption={[Constants]Defining a constant for the dead tree object.},label={constex}]{code/3/deadtree.rms}

There will be a table of **all** constants with names *and* without names
for your convenience later in this guide. Check the table of contents for a page number.

### Sections

A random map script is divided into *seven sections*. Specific parts of your script will
go into each section. A section *begins* with the section name enclosed in `< >` and *ends* when
you start a new one. See \autoref{sections} for an example.

Note that the sections are shown in a particular order. You *can* place the sections in any order you like.
However, **the order in which I have presented the sections is the order in which the game will read them**.
In order to avoid confusion, I strongly recommend you use the same order for your sections. This will help
you figure why your script is behaving the way it is.

\lil[caption={[RMS sections]The seven sections of a random map script.},label={sections}]{code/3/sections.rms}

### Blocks

#### Fields





# Outline of a Script

## The Preamble

## Player Setup

## Land Generation

## Elevation Generation

## Terrain Generation

## Connection Generation

## Object Generation

### Player Towns

#### Regicide Support

### Arena Style Maps

### Resources

### Eye Candy





# Constants

Information for this section based on [Zetnus' RMS Guide](http://aok.heavengames.com/blacksmith/showfile.php?fileid=12178).

The tables are divided into:

1. Buildings
1. Units
   i) Player
   i) Gaia
1. Resource Objects
1. Terrains/Lands
   i) Normal Terrain
   i) Forest
   i) Water

The columns are divided into:

1. Description
   - A brief description of the object/terrain
   - Extra information here 

## Buildings

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
Town Center\                    TOWN_CENTER           109
Use with
`set_place_for_every_player`

\

Wall\                            WALL\                  117
Use with                        STONE_WALL                   
`set_place_for_every_player`
Only works if player lands
are connected

\
                                
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------

## Units

### Player Units

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------

### Gaia Units

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------

## Resource Objects

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------

## Terrains/Lands

### Normal Terrain

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------

### Forest

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------

### Water

--------------------------------------------------------------
Description                     Name                  Number
------------------------------  --------------------  --------
'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '

'                               '                     '
--------------------------------------------------------------



# Example Scripts

## My Script Template
[This is the template I use to create all my scripts](https://raw.githubusercontent.com/HousedHorse/hh-rms-aoe2/master/template.rms).
I find it very easy to start with this file and edit it to my liking. Clicking the link at the beginning
of this paragraph will allow you to copy and paste it.

I have included some extra constants for convenience as well as comments listing popular alternatives
to boars, wolves, sheep, forests, etc.

The default settings are for a standard Arabia map. You can change them however you like.

## My GitHub

Check out my [GitHub repository](https://github.com/HousedHorse/hh-rms-aoe2) which contains all the RMS scripts I have ever written.

Caution: some of these scripts are old and crappy!

## My Steam Workshop

You can also check out my [Steam Workshop page](https://steamcommunity.com/id/housedhorse/myworkshopfiles/?appid=221380).
